language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sahala/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sahala/docker-react npm run test